# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.17

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          # version: v1.41.1
          version: v1.49.0
          working-directory: ${{ env.BRANCH }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -v -count=100 -race -timeout=1m ./...
        working-directory: ${{ env.BRANCH }}

      - name: Optimization tests
        run: go test -v -count=1 -timeout=1m -tags bench ./...
        working-directory: ${{ env.BRANCH }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.14

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint
        working-directory: ${{ env.BRANCH }}

      - name: make build
        run: make build
        working-directory: ${{ env.BRANCH }}
